# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  app_version: '1.0.$(Build.BuildId)'
  app_name: 'helloworld'
  ORG_NAME: 'slavikb1'
  branchName:  $(Build.SourceBranchName) 
  nupkg_path: $(System.DefaultWorkingDirectory)/$(app_name)/bin/Release/$(app_name).$(app_version).nupkg
  dll_path:   $(System.DefaultWorkingDirectory)/$(app_name)/bin/Debug/net8.0/$(app_name).dll

steps:
  
- script: dotnet build .csproj
  displayName: 'Build the artifact'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'c20c9286-9ec3-4611-af80-efb9055a385f'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c20c9286-9ec3-4611-af80-efb9055a385f'
